export const clerkAppearance = {
  variables: {
    colorPrimary: '#34584c',
    colorText: '#333333',
    colorTextSecondary: '#6b6b6b',
    colorBackground: '#ffffff',
    colorInputBackground: '#ffffff',
    colorInputText: '#333333',
    borderRadius: '0.75rem',
    fontSize: '14px',
  },
  elements: {
    rootBox: 'w-full max-w-[420px]',
    card: 'w-full rounded-2xl border border-[#e8e8e4] bg-white shadow-none px-6 py-8 sm:px-8',
    cardBox: 'w-full shadow-none',
    main: 'w-full gap-4',
    headerTitle: 'text-xl font-semibold text-[#333333]',
    headerSubtitle: 'text-sm text-[#6b6b6b]',
    form: 'w-full gap-4',
    formFieldRow: 'flex flex-col gap-4 sm:flex-row',
    formField: 'w-full',
    formFieldLabel: 'text-xs font-medium text-[#6b6b6b]',
    formFieldInput:
      'h-11 w-full rounded-xl border border-[#e8e8e4] bg-white px-3.5 text-sm text-[#333333] focus:border-[#34584c]',
    formFieldInputShowPasswordButton: 'text-[#6b6b6b]',
    phoneInputBox: 'h-11 rounded-xl border border-[#e8e8e4]',
    formButtonPrimary:
      'h-11 w-full rounded-full bg-[#34584c] text-sm font-semibold normal-case shadow-none hover:bg-[#253f36]',
    footer: 'bg-transparent',
    footerAction: 'text-sm text-[#6b6b6b]',
    footerActionLink: 'font-semibold text-[#34584c] hover:text-[#253f36]',
    identityPreview: 'rounded-xl border border-[#e8e8e4]',
    formFieldSuccessText: 'text-sm',
    formFieldErrorText: 'text-sm text-[#c1443a]',
    dividerLine: 'bg-[#e8e8e4]',
    dividerText: 'text-[#6b6b6b]',
    socialButtonsBlockButton: 'h-11 rounded-xl border border-[#e8e8e4]',
    alternativeMethodsBlockButton: 'h-11 rounded-xl border border-[#e8e8e4]',
  },
};
